### ISSUE TITLE
ssh join.5monkeys.se <Permission denied (publickey)>

### ISSUE THREAD

**Issue by devfemibadmus** [5monkeys/5monkeys.github.io#30]
at https://www.5monkeys.se/ you said 

Would you like to know more about our job offers?
> ssh join.5monkeys.se

1: user not define
2: can't use publickey

**Comment by bossegranat** [comment]
Find the user and the key. I solved this at the bar with Termux. Tip: It's a challenge.

**Comment by devfemibadmus** [comment]
Oh......new here thou
